function [fitresult, gof] = fit_rho(p, T, rho)
%CREATEFIT1(P,T,RHO)
%  Create a fit.
%
%  Data for 'rho(p,T)' fit:
%      X Input: p
%      Y Input: T
%      Z Output: rho
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Mar-2023 13:05:10


%% Fit: 'rho(p,T)'.
[xData, yData, zData] = prepareSurfaceData( p, T, rho );

% Set up fittype and options.
ft = 'linearinterp';
opts = fitoptions( 'Method', 'LinearInterpolant' );
opts.ExtrapolationMethod = 'linear';
opts.Normalize = 'on';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'rho(p,T)' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'rho(p,T)', 'rho vs. p, T', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'p', 'Interpreter', 'none' );
ylabel( 'T', 'Interpreter', 'none' );
zlabel( 'rho', 'Interpreter', 'none' );
grid on


