function [fitresult, gof] = fit_beta(p, T, beta)
%CREATEFIT(P,T,BETA)
%  Create a fit.
%
%  Data for 'beta(p,T)' fit:
%      X Input: p
%      Y Input: T
%      Z Output: beta
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Mar-2023 13:06:12


%% Fit: 'beta(p,T)'.
[xData, yData, zData] = prepareSurfaceData( p, T, beta );

% Set up fittype and options.
ft = 'linearinterp';
opts = fitoptions( 'Method', 'LinearInterpolant' );
opts.ExtrapolationMethod = 'linear';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'beta(p,T)' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'beta(p,T)', 'beta vs. p, T', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'p', 'Interpreter', 'none' );
ylabel( 'T', 'Interpreter', 'none' );
zlabel( 'beta', 'Interpreter', 'none' );
grid on


