function [fitresult, gof] = fit_h(p, T, h)
%CREATEFIT(P,T,H)
%  Create a fit.
%
%  Data for 'h(p,T)' fit:
%      X Input: p
%      Y Input: T
%      Z Output: h
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Mar-2023 12:56:06


%% Fit: 'h(p,T)'.
[xData, yData, zData] = prepareSurfaceData( p, T, h );

% Set up fittype and options.
ft = 'linearinterp';
opts = fitoptions( 'Method', 'LinearInterpolant' );
opts.ExtrapolationMethod = 'linear';
opts.Normalize = 'on';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'h(p,T)' );
h_1 = plot( fitresult, [xData, yData], zData );
legend( h_1, 'h(p,T)', 'h vs. p, T', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'p', 'Interpreter', 'none' );
ylabel( 'T', 'Interpreter', 'none' );
zlabel( 'h', 'Interpreter', 'none' );
grid on
view( -45.1, 53.8 );


