function [fitresult, gof] = fit_Pr(p, T, Pr)
%CREATEFIT(P,T,PR)
%  Create a fit.
%
%  Data for 'Pr(p,T)' fit:
%      X Input: p
%      Y Input: T
%      Z Output: Pr
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Mar-2023 13:07:18


%% Fit: 'Pr(p,T)'.
[xData, yData, zData] = prepareSurfaceData( p, T, Pr );

% Set up fittype and options.
ft = 'linearinterp';
opts = fitoptions( 'Method', 'LinearInterpolant' );
opts.ExtrapolationMethod = 'linear';
opts.Normalize = 'on';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Pr(p,T)' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'Pr(p,T)', 'Pr vs. p, T', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'p', 'Interpreter', 'none' );
ylabel( 'T', 'Interpreter', 'none' );
zlabel( 'Pr', 'Interpreter', 'none' );
grid on
view( -27.1, 45.0 );


