function [fitresult, gof] = fit_eta(p, T, eta)
%CREATEFIT(P,T,ETA)
%  Create a fit.
%
%  Data for 'eta(p,T)' fit:
%      X Input: p
%      Y Input: T
%      Z Output: eta
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Mar-2023 13:06:48


%% Fit: 'eta(p,T)'.
[xData, yData, zData] = prepareSurfaceData( p, T, eta );

% Set up fittype and options.
ft = 'linearinterp';
opts = fitoptions( 'Method', 'LinearInterpolant' );
opts.ExtrapolationMethod = 'linear';
opts.Normalize = 'on';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'eta(p,T)' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'eta(p,T)', 'eta vs. p, T', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'p', 'Interpreter', 'none' );
ylabel( 'T', 'Interpreter', 'none' );
zlabel( 'eta', 'Interpreter', 'none' );
grid on


