function [fitresult, gof] = fit_c_p(p, T, c_p)
%CREATEFIT(P,T,C_P)
%  Create a fit.
%
%  Data for 'c_p(p,T)' fit:
%      X Input: p
%      Y Input: T
%      Z Output: c_p
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Mar-2023 13:05:45


%% Fit: 'c_p(p,T)'.
[xData, yData, zData] = prepareSurfaceData( p, T, c_p );

% Set up fittype and options.
ft = 'linearinterp';
opts = fitoptions( 'Method', 'LinearInterpolant' );
opts.ExtrapolationMethod = 'linear';
opts.Normalize = 'on';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'c_p(p,T)' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'c_p(p,T)', 'c_p vs. p, T', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'p', 'Interpreter', 'none' );
ylabel( 'T', 'Interpreter', 'none' );
zlabel( 'c_p', 'Interpreter', 'none' );
grid on


